"""The convolution integral, slid across by hand, in dice units.

    p_{X+Y}(z) = \\int p_X(x)\\, p_Y(z - x)\\, dx

A die takes values 1 to 6, so take the continuous version of one: uniform on
[1, 6], p(x) = 1/5. The integrand is then that box held still and a second box
reflected and shifted by z. The integral at each z is the area where they overlap,
which grows from nothing at z = 2, reaches its largest at z = 7 -- the total two
dice make most often -- and shrinks away by z = 12.

Same triangle as the dice, same peak in the same place, without the discreteness:
the point is where the limits of integration come from, and they are the edges of
the green overlap, max(1, z-6) to min(6, z-1).

Top panel: the two boxes and their overlap. Bottom panel: the resulting pdf, traced
as z advances, with a marker whose height is the shaded area above it.

Two consumers, one definition:

    # in a notebook, for class: an inline player with play/pause/scrub
    %run ../scripts/anim_convolution.py
    HTML(convolution_animation().to_jshtml())

    # on the command line, to refresh the committed GIF for readers
    python3 notebooks/scripts/anim_convolution.py --save

The GIF matters because notebook *outputs* are stripped from the published student
copy, so an animation generated by a cell is invisible to anyone who has not run it.
A committed file referenced from a markdown cell survives.
"""

import numpy as np
from matplotlib import pyplot as plt
from matplotlib.animation import FuncAnimation

LO, HI = 1.0, 6.0               # a die's range
WIDTH = HI - LO                 # 5
HEIGHT = 1.0 / WIDTH            # 1/5, so the box integrates to 1
FRAMES = 81
ZMIN, ZMAX = 2.0 - 0.25, 12.0 + 0.25


def overlap(z: float) -> float:
    """Length shared by [1, 6] and [z-6, z-1] -- the integral's limits, in dice units."""
    return max(0.0, min(HI, z - LO) - max(LO, z - HI))


def convolution_animation() -> FuncAnimation:
    zs = np.linspace(ZMIN, ZMAX, FRAMES)
    tri = np.array([overlap(z) * HEIGHT * HEIGHT for z in zs])   # area of the overlap

    fig, (top, bot) = plt.subplots(2, 1, figsize=(7.4, 5.5), sharex=True,
                                   gridspec_kw={"height_ratios": [1.3, 1]})

    # --- top: the integrand --------------------------------------------------
    top.add_patch(plt.Rectangle((LO, 0), WIDTH, HEIGHT, facecolor="C0", alpha=0.25,
                                edgecolor="C0", lw=2, label="one die, $p_X(x)$"))
    slider = plt.Rectangle((0, 0), WIDTH, HEIGHT, facecolor="none", edgecolor="C1",
                           lw=2, ls="--", label="the other, $p_Y(z-x)$")
    top.add_patch(slider)
    shade = top.fill_between([], [], color="C2", alpha=0.55)
    marker = top.axvline(0, color="0.4", lw=1, ls=":")
    top.set_xlim(ZMIN - WIDTH - 0.4, ZMAX + 0.4)
    top.set_ylim(0, HEIGHT * 1.75)
    top.set_xticks(np.arange(-4, 14, 1))
    top.set_ylabel("density")
    top.legend(loc="upper left", fontsize=9, ncol=2, framealpha=0.95)
    top_title = top.set_title("$z = 2.00$   overlap $= 0.00$")

    # --- bottom: the integral it traces out ----------------------------------
    bot.plot(zs, tri, color="0.82", lw=1.5)
    drawn, = bot.plot([], [], color="C2", lw=2.5)
    dot, = bot.plot([], [], "o", color="C2", ms=7)
    bot.axvline(7, color="0.6", lw=1, ls=":")
    bot.text(7.1, 0.205, "7, the most likely total", fontsize=8.5, color="0.35")
    bot.set_ylim(0, 0.235)
    bot.set_xlabel("$z$ — the total of the two dice   (and $x$, for the panel above)")
    bot.set_ylabel("$p_{X+Y}(z)$")
    fig.tight_layout()

    def frame(i):
        nonlocal shade
        z = zs[i]
        slider.set_x(z - HI)
        lo, hi = max(LO, z - HI), min(HI, z - LO)
        shade.remove()
        if hi > lo:
            shade = top.fill_between([lo, hi], HEIGHT, color="C2", alpha=0.55)
        else:
            shade = top.fill_between([], [], color="C2", alpha=0.55)
        marker.set_xdata([z, z])
        top_title.set_text(f"$z = {z:0.2f}$   overlap $= {overlap(z):0.2f}$")
        drawn.set_data(zs[:i + 1], tri[:i + 1])
        dot.set_data([z], [tri[i]])
        return slider, drawn, dot

    return FuncAnimation(fig, frame, frames=FRAMES, interval=90, blit=False)


if __name__ == "__main__":
    import sys
    from pathlib import Path

    # Guarded so `%run` in a notebook only defines the function. %run sets
    # __name__ to "__main__", so an unguarded block here would rewrite the GIF
    # every time the cell is executed in class.
    if "--save" in sys.argv:
        out = Path(__file__).resolve().parent.parent / "figures" / "convolution-two-dice.gif"
        out.parent.mkdir(parents=True, exist_ok=True)
        convolution_animation().save(out, writer="pillow", fps=12, dpi=80)
        print(f"wrote {out} ({out.stat().st_size / 1024:.0f} KB)")
